apiVersion: v1
kind: Service
metadata:
  name: "pokemon"
spec:
  selector:
    app: "pokemon-api"
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 80
      nodePort: 31000
  type: NodePort

