apiVersion: v1
kind: Services
metadata:
  name: "pokemon"
spec:
  selector:
    app: "pokemon-api"
  ports:
    protocol: "TCP"
    port: 80
    targetPort: 10080
    nodePort: 31000
  type: NodePort

