apiVersion: v1
kind: Pod
metadata:
  name: "pokemon"
  labels:
    app: pokemon-api
spec:
  containers:
    - name: pokemon-api
      image: vcashik/pokemon-app:1.0.1
      ports:
        - name: http
          containerPort: 80
        - name: health
          containerPort: 81
      resources:
        limits:
          cpu: "250m"
          memory: "128Mi"
      livenessProbe:
        httpGet:
          path: /liveness_test
          port: health
          scheme: HTTP
        initialDelaySeconds: 5
        periodSeconds: 15
        timeoutSeconds: 5
      readinessProbe:
        httpGet:
          path: /readinessBeamer
          port: health
          scheme: HTTP
        initialDelaySeconds: 5
        timeoutSeconds: 1
